version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: disonds-hometube_web_1
      APP_PORT: 8501

  web:
    image: ghcr.io/egalitarianmonkey/hometube:v2.10.0@sha256:5e205725259336ecf9e2ce02261da114e7e9076cacc9b4b04bff6ce9117994af
    restart: on-failure
    environment:
      TZ: ${TZ:-UTC}
      UI_LANGUAGE: en
      VIDEOS_FOLDER: /data/videos
      TMP_DOWNLOAD_FOLDER: /data/tmp
      YOUTUBE_COOKIES_FILE_PATH: /config/youtube_cookies.txt
    volumes:
      - ${UMBREL_ROOT}/data/storage/downloads/hometube:/data/videos
      - ${APP_DATA_DIR}/data/tmp:/data/tmp
      - ${APP_DATA_DIR}/data/config:/config
