#!/usr/bin/env bash
set -euo pipefail

UMBREL_STORAGE_DOWNLOADS_HOMETUBE_DIR="${UMBREL_ROOT}/data/storage/downloads/hometube"
DESIRED_OWNER="1000:1000"

if [[ ! -d "${UMBREL_STORAGE_DOWNLOADS_HOMETUBE_DIR}" ]]; then
  mkdir -p "${UMBREL_STORAGE_DOWNLOADS_HOMETUBE_DIR}"
fi

hometube_correct_permission() {
  local -r path="${1}"

  if [[ -d "${path}" ]]; then
    owner=$(stat -c "%u:%g" "${path}")

    if [[ "${owner}" != "${DESIRED_OWNER}" ]]; then
      chown "${DESIRED_OWNER}" "${path}"
    fi
  fi
}

hometube_correct_permission "${UMBREL_STORAGE_DOWNLOADS_HOMETUBE_DIR}"
